### ISSUE TITLE
CVC-14 dataset

### ISSUE THREAD

**Issue by lihui1998** [sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection#11]
Hello, could you please provide the data loading code for training the CVC-14 dataset? The CVC-14 dataset cannot be trained in the current code.thanks.

**Comment by socome** [comment]
Thank you for your interest in our work. We can provide the data loading code for training the CVC-14, but it is not a clean code.

[datasets.zip](https://github.com/sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection/files/8038078/datasets.zip)
