### ISSUE TITLE
Question about categories

### ISSUE THREAD

**Issue by byminji** [sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection#14]
Hi,

Thank you for your great work.
I have two questions about the category setting of the model.

1. I have noticed that the categories (classes) in KAIST-RGBT dataset annotation are ['ignore', 'person', 'cyclist', 'people', 'person?'], but the number of categories in the config file is set to three. What exactly does each category id mean in the model?

2. If my understanding is correct, the evaluation script converts the predicted result into a json format for submission to the evaluation server, where all the predictions are made to have a category_id of 1. Are the results of the model's detection considered as only one category because all the classes predicted by the model are sub-categories of 'pedestrian'?

Thank you.

**Comment by socome** [comment]
Thank you for your interest in our work. 

1. We follow [this comment](https://github.com/CalayZhou/MBNet/issues/10#issuecomment-694736996), so we Integrate all the classes into 'person' without 'ignore'. And the meaning of 'number of categories' in the config file is ['ignore', 'visible only', 'thermal only'] and that is the condtribution of our paper. Please refer to our paper for more detailed information. [link](https://ieeexplore.ieee.org/document/9496129)

2. Yes. 

If you want to know more details about our paper, please refer to our paper for more detailed information. [link](https://ieeexplore.ieee.org/document/9496129).

**Comment by byminji** [comment]
Thanks for your quick reply:) 감사합니다!

**Comment by socome** [comment]
Feel free to send me a quick e-mail if you have more questions. 감사합니다.
