### ISSUE TITLE
Testing on unpaired images

### ISSUE THREAD

**Issue by FusionModele** [sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection#15]
Hi,
How can i test the following model on unpaired images , i can't found where do i need to make changes to make it work.
Thanks in advance.

**Comment by socome** [comment]
Thank you for your interest in our work.

We provide the Shell Script file to test the model on unpaired dataset. Please check this [link](https://github.com/sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection/blob/main/src/FDZ_exp.sh). Thank you.

**Comment by FusionModele** [comment]
Hi @socome , thanks for your reply.

**Comment by socome** [comment]
@FusionModele Plz refer to [our paper](https://ieeexplore.ieee.org/document/9496129).

**Comment by FusionModele** [comment]
Thank you @socome ,
When i have tested this script on the same  test_images i didn't get a detection result on blackout_r and blackout_t why ?

**Comment by socome** [comment]
@FusionModele I think that was occurred by high min_score in [this code](https://github.com/sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection/blob/8e583929a97b9f959634efa69174435ad0252a57/src/vis.py#L54). In other word, The final confidence of our model is the average score(rgb,thermal). Thus, plz change the min_socre to about 0.3, but i'm not sure..

**Comment by FusionModele** [comment]
Okay @socome thanks for ur reply.
how Can i run inference using a video?

**Comment by socome** [comment]
I don't know the meaning of demo video. If [it](https://github.com/sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection/blob/main/Doc/figure/video.gif) is the demo video, we don't have the code for making the demo video. I'm sorry. However, I believe that you can make the demo video using our public codes !

**Comment by FusionModele** [comment]
I mean that i want to give a video like input and visualise the result of detection on this video.

**Comment by socome** [comment]
When you choose the 'sidesblackout_a'. 'sidesblackout_b' ,'surroundingblackout' options, you can get the blended images. and then  you make the videos. If you need to get the results of other methods(MBNet, AR-CNN, MSDS), i try to find the result file tomorrow.

By the way, Can I ask why you need it?

### Images to Video
```
import cv2
import numpy as np
import glob
 
img_array = []

for filename in sorted(glob.glob('./Detection_visualization/*.jpg')):
    img = cv2.imread(filename)
    height, width, layers = img.shape
    size = (width,height)
    img_array.append(img)
    print(filename)
 
 
out = cv2.VideoWriter('test_txt.avi',cv2.VideoWriter_fourcc(*'DIVX'), 5, size)
 
for i in range(len(img_array)):
    out.write(img_array[i])
    print(i)
out.release()
```

**Comment by FusionModele** [comment]
Thanks for your quick reply.

**Comment by wlc-git1** [comment]
Hi @socome ,
Thanks for your work.
could you provide the file  of the detection result on videos.
Thanks!

**Comment by xown3197** [comment]
Hi, @wlc-git1,

You can check the [result](https://github.com/sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection/tree/main/evaluation_script/state_of_arts) file here.
