### ISSUE TITLE
Run inference on unpaired images

### ISSUE THREAD

**Issue by TRTmm** [sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection#16]
Hi , 
I would like to know more about the two types of unpaired cases: RGB blackout and Thermal blackout.
 I have read the paper but on the code it seems like you test on both visible and thermal images even we mention the option --FDZ blackout_r  or blackout_t  when running the inference file.
On visualisation the visible or thermal image depending on the case are  fill  zero values but on evaluation you work with both images visible and thermal, so How the testing of inference  working on in the case of unpaired images?

Thanks in advance.

**Comment by socome** [comment]
Thank you for your interest in our work.

When you evaluate the model with FDZ options, the input(rgb or thermal) is changed to zero value. please refer to [here](https://github.com/sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection/blob/8e583929a97b9f959634efa69174435ad0252a57/src/inference.py#L110) and [here](https://github.com/sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection/blob/8e583929a97b9f959634efa69174435ad0252a57/src/utils/transforms.py#L121).
