### ISSUE TITLE
Train on custom data

### ISSUE THREAD

**Issue by TRTmm** [sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection#17]
Hi , since i am very interested in your work, i like to reproduce it with my own dataset but i got this error .

Error : stack expects each tensor to be equal size, but got [3, 720, 1280] at entry 0 and [3, 512, 640] at entry 1
(NB : my image dimension is 1280x720)

**Comment by rgw117** [comment]
Hi, thank you for your interest in our work. We recommend simply resizing the input shape to 512*640 as it is used in our paper. However, if you indeed need to use the original resolution, then you will need to change some of the codes for the initial parameters of prior anchor boxes. Please, refer to the [link](https://github.com/sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection/blob/8e583929a97b9f959634efa69174435ad0252a57/src/model.py#L470) and change some parameters after referring to [SSD tutorial](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Object-Detection). Thank you.
