### ISSUE TITLE
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed

### ISSUE THREAD

**Issue by xu19971109** [sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection#19]
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed
how to fix it?

**Comment by rgw117** [comment]
Did you mean you got the error while building a docker container? Please, refer to [link1](https://forums.developer.nvidia.com/t/gpg-error-http-developer-download-nvidia-com-compute-cuda-repos-ubuntu1804-x86-64/212904) and [link2](https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212771).
