### ISSUE TITLE
May I ask if the updated test_annotations are for vis or lwir?

### ISSUE THREAD

**Issue by xu19971109** [sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection#20]

**Comment by rgw117** [comment]
Thank you for your interest in our work. The test annotations provided are the sanitized version of the original annotations (lwir). But they can be used for both RGB and lwir as the KAIST dataset is pixel-level aligned. Please, refer to https://arxiv.org/pdf/1808.04818.pdf for more details.
