### ISSUE TITLE
Why only the targets with height > 50 are evaluated for total Miss Rate metric in evaluation_scipt.py?

### ISSUE THREAD

**Issue by CyberPegasus** [sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection#21]
I am puzzled about the height range defined in evaluation_script.py, i.e., self.HtRng of class KAISTParams.
It seems to set the targets with height less than 50 to be ignored in evaluation process. 
And if we set the lower bound of height range to 16 or 30, which is lower than the classic boundary 32*32 for small targets in COCO, it can be found an evident decay in detection precison, i.e., an evident increasing of MR.
Could you please give the reason for the specific setting of height range ?

**Comment by socome** [comment]
@CyberPegasus Thank you for your interest in our work.

Please, refer to "[Multispectral Pedestrian Detection: Benchmark Dataset and Baseline](https://soonminhwang.github.io/rgbt-ped-detection)".

"For this experiment, we used a subset named **reasonable** which is a representative subset of the proposed dataset. The reasonable subset consists of not/partially occluded pedestrians which are larger than 55 pixels. "

**Comment by CyberPegasus** [comment]
Thanks for your reply ~
