### ISSUE TITLE
Question about the necessary preprocessing details of CVC-14 training set conducted by MLPD

### ISSUE THREAD

**Issue by CyberPegasus** [sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection#23]
Thank you for your previous tracking on all the issues.
Since your released codes mainly focus on KAIST, could you please provide with the necessary preprocessing details of CVC-14 dataset conducted by MLPD? 
-----------------------------------------------------------
Besides, your paper points out that "However, the author of the dataset released the cropped image pairs without the non-overlapped areas. Therefore, we treated this dataset as a fully-overlapped (paired) dataset for our purpose,...".
Thus I am wondering if the CVC-14 for MLPD are cleaned by filtering out the targets not belong to "the cropped image pairs without the non-overlapped areas" for training?

**Comment by socome** [comment]
Thank you for your interest in our research. 

1. Unfortunately, due to graduation and other reasons, we no longer have access to the experiment code about CVC-14 dataset . We apologize for any inconvenience. 

2. We trained our model on the entire CVC-14 dataset without any filtering.
