### ISSUE TITLE
About the cuda memory

### ISSUE THREAD

**Issue by medicineqian** [sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection#24]
As shown in the figure below, I have a memory explosion problem when running the code, there is no problem with the model training, but when running to val_epoch there will be memory explosion, that is, when running to the line of detect_object() in the inference.py there will be not enough memory.
![K{(AK5V@`49 U1FIQJLG${2](https://github.com/sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection/assets/74084955/83ef8431-e020-456e-9f1d-dc5d3c47ceb5)

**Comment by socome** [comment]
@medicineqian 

I'm not sure. It seems like the model isn't trained enough for evaluation. 
(That is, the trained model predicts too many bounding boxes, leading to a memory explosion)
To solve the problem, try to evaluate the model after 5 epochs.

```
if epoch > 5 : 
     val_epoch()
```
