### ISSUE TITLE
how to get result of qualitative??? 

### ISSUE THREAD

**Issue by luke0709** [sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection#7]

**Comment by xown3197** [comment]
Thank you for your interest in our work.
We'll update it by the end of the day.

**Comment by luke0709** [comment]
Thankyou!!

**Comment by wlc-git** [comment]
May I ask how can I get the test picture and the sample that can detect pedestrians, just like the video shown? Looking forward to your reply, thank you

**Comment by socome** [comment]
We will also update it. @wlc-git

**Comment by xown3197** [comment]
We updated the visualization code.
Please refer to this [section](https://github.com/sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection#inference)

**Comment by luke0709** [comment]
Thank you for your work. 

I have a error while running inference.py 
It is
 AttributeError: module 'torch' has no attribute 'permute'
So I changed code
 original_image = original_image.permute(1, 2, 0).contiguous()
from 
original_image = torch.permute(original_image.squeeze(), (1, 2, 0)) 

but exist error about number of dims don't match in permute

I checked original image shape (1,1,512,640)

Is there any error while running?? 

Looking forward to your reply, 

thank you

**Comment by rgw117** [comment]
Please, refer to [#8](https://github.com/sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection/issues/8)
