### ISSUE TITLE
error in vis.py

### ISSUE THREAD

**Issue by luke0709** [sejong-rcv/MLPD-Multi-Label-Pedestrian-Detection#8]
Thank you for your work.

I have a error while running inference.py
It is
AttributeError: module 'torch' has no attribute 'permute'
So I changed code
original_image = original_image.permute(1, 2, 0).contiguous()
from
original_image = torch.permute(original_image.squeeze(), (1, 2, 0))

but exist error about number of dims don't match in permute

I checked original image shape (1,1,512,640)

Is there any error while running??

Looking forward to your reply,

thank you

**Comment by rgw117** [comment]
Did you run the code in the Docker container we provided?

**Comment by rgw117** [comment]
Thank you for your interest in our work. We think the issue was caused by Pytorch version. Now, we fixed the problem and updated the fixed code.
